repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.18.1
  hooks:
  - id: gitleaks
    name: gitleaks
    entry: docker
    args: ['run', '--rm', '-v', '${PWD}:/repo', 'ghcr.io/gitleaks/gitleaks:latest', 'gitleaks', '--path', '/repo']
    language: docker
# - repo: local
#   hooks:
#   - id: maven-test
#     name: maven-test
#     entry: mvn
#     args: ['test']
#     language: system
