repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.1
  hooks:
  - id: gitleaks
    name: gitleaks
    entry: docker
    args: ['run', '-v', '${ChallengePackage/devops-project}:/go/src/github.com/gitleaks/gitleaks', 'golang:1.19', 'sh', '-c', 'cd /go/src/github.com/gitleaks/gitleaks && go build -o /go/src/github.com/gitleaks/gitleaks/bin/gitleaks ./cmd']
    language: system
    pass_filenames: false
    files: '.*'






# - repo: local
#   hooks:
#   - id: maven-test
#     name: maven-test
#     entry: mvn
#     args: ['test']
#     language: system
