repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.1
  hooks:
  - id: gitleaks
    name: gitleaks
    entry: docker
    args: ['run', '-v', '${ChallengePackage/devops-project}:/path', '-e', 'VERSION=v0.0.1', 'ghcr.io/gitleaks/gitleaks:latest', 'sh', '-c', 'CGO_ENABLED=0 go build -o bin/gitleaks -ldflags "-X=github.com/zricethezav/gitleaks/v8/cmd.Version=$VERSION"']
    language: docker

# - repo: local
#   hooks:
#   - id: maven-test
#     name: maven-test
#     entry: mvn
#     args: ['test']
#     language: system
