repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.17.0
  hooks:
  - id: gitleaks
    name: gitleaks
    entry: docker
    args: ['run', '-v', '/home/ec2-user/A-DevopsChallenge/ChallengePackage/devops-project:/go/src/github.com/gitleaks/gitleaks', 'golang:1.19', 'sh', '-c', 'rm -rf /go/src/github.com/gitleaks/gitleaks && git clone --branch v8.18.1 https://github.com/zricethezav/gitleaks.git /go/src/github.com/gitleaks/gitleaks && cd /go/src/github.com/gitleaks/gitleaks && go build -o /go/bin/gitleaks github.com/gitleaks/gitleaks/v8/cmd/gitleaks']
    language: system
    pass_filenames: false
    files: '.*'






# - repo: local
#   hooks:
#   - id: maven-test
#     name: maven-test
#     entry: mvn
#     args: ['test']
#     language: system
