repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: trufflehog
    name: trufflehog
    entry: bash
    args: ['-c', 'sudo curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin && trufflehog --entropy=True --exclude_paths=vendor --max_depth=20 --regex']
    language: system
    pass_filenames: false
    files: ^.*$
    exclude: ^$ # Exclude empty files
    always_run: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0 # Use the latest release of pre-commit-hooks
  hooks:
  - id: detect-secrets
    args: ['--custom-plugins', 'detect_secrets.plugins.aws_secrets', '--baseline', '.secrets.baseline']
